<template>
  <section class="settings-view"><header><p>SETTINGS</p><h1>把纪念册变成我们的样子</h1></header><div class="settings-grid"><section class="settings-card"><div class="card-title"><span class="material-symbols-outlined">favorite</span><div><h2>关系信息</h2><p>用于计算相恋天数和页面称呼</p></div></div><label>在一起的第一天<input v-model="startDate" type="date"></label><label>对方名字<input v-model.trim="partnerName" maxlength="16" placeholder="输入昵称"></label><button class="save-settings" type="button" @click="saveRelationship">保存关系信息</button></section><section class="settings-card anniversaries"><div class="card-title"><span class="material-symbols-outlined">event</span><div><h2>自定义纪念日</h2><p>每年都会自动计算下一次日期</p></div><button type="button" @click="addAnniversary"><span class="material-symbols-outlined">add</span>添加</button></div><div class="anniversary-editor"><div v-for="item in anniversaryDrafts" :key="item.id"><input v-model.trim="item.name" aria-label="纪念日名称" placeholder="纪念日名称"><input v-model="item.date" aria-label="纪念日日期" type="date"><button type="button" aria-label="删除纪念日" @click="removeAnniversary(item.id)"><span class="material-symbols-outlined">delete</span></button></div></div><button class="save-settings" type="button" @click="saveAnniversaries">保存纪念日</button></section><section class="settings-card data-card"><div class="card-title"><span class="material-symbols-outlined">database</span><div><h2>数据管理</h2><p>导出备份，或从备份恢复记录</p></div></div><div class="data-actions"><button type="button" @click="$emit('export')"><span class="material-symbols-outlined">download</span><span><b>导出 JSON</b><small>下载全部记录与设置</small></span></button><label><input type="file" accept="application/json" @change="handleImport"><span class="material-symbols-outlined">upload</span><span><b>导入 JSON</b><small>从备份文件恢复</small></span></label><button class="danger" type="button" @click="confirmClear"><span class="material-symbols-outlined">delete_forever</span><span><b>清空所有记录</b><small>此操作无法撤销</small></span></button></div></section></div></section>
</template>
<script setup lang="ts">
import { ref, watch } from 'vue'
import type { Anniversary, RelationshipInfo } from '../types/records'
const props = defineProps<{ relationship: RelationshipInfo }>()
const emit = defineEmits<{ relationship: [startDate: string, partnerName: string]; anniversaries: [items: Anniversary[]]; export: []; import: [file: File]; clear: [] }>()
const startDate = ref(props.relationship.startDate)
const partnerName = ref(props.relationship.partnerName)
// props 来自 Vue 响应式对象，不能直接 structuredClone；显式复制字段可避免 DataCloneError。
const anniversaryDrafts = ref<Anniversary[]>(props.relationship.anniversaries.map((item) => ({ ...item })))
watch(() => props.relationship, (relationship) => {
  startDate.value = relationship.startDate
  partnerName.value = relationship.partnerName
  anniversaryDrafts.value = relationship.anniversaries.map((item) => ({ ...item }))
}, { deep: true })
function saveRelationship(): void { emit('relationship', startDate.value, partnerName.value) }
function addAnniversary(): void { anniversaryDrafts.value.push({ id: crypto.randomUUID(), name: '', date: new Date().toISOString().slice(0, 10) }) }
function removeAnniversary(id: string): void { anniversaryDrafts.value = anniversaryDrafts.value.filter((item) => item.id !== id) }
function saveAnniversaries(): void { emit('anniversaries', anniversaryDrafts.value.filter((item) => item.name && item.date).map((item) => ({ ...item }))) }
function handleImport(event: Event): void { const input = event.target as HTMLInputElement; const file = input.files?.[0]; if (file) emit('import', file); input.value = '' }
function confirmClear(): void { if (window.confirm('确定清空所有恋爱记录吗？建议先导出备份。此操作无法撤销。') && window.confirm('再次确认：真的要清空全部记录吗？')) emit('clear') }
</script>
<style scoped>
.settings-view{padding:28px;position:relative}.settings-view>header p{margin:0 0 3px;color:#ff657d;font-size:8px;font-weight:800;letter-spacing:.15em}.settings-view>header h1{margin:0;color:#4b393a;font-size:19px}.settings-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:18px}.settings-card{padding:18px;border:1px solid #f0e4df;border-radius:12px;background:#fff;box-shadow:0 4px 16px rgba(58,39,38,.05)}.card-title{display:flex;align-items:center;gap:10px;margin-bottom:17px}.card-title>.material-symbols-outlined{display:grid;place-items:center;width:36px;height:36px;border-radius:10px;color:#ff667e;background:#ffecec;font-size:19px}.card-title h2,.card-title p{margin:0}.card-title h2{color:#564445;font-size:12px}.card-title p{margin-top:2px;color:#ad9b98;font-size:8px}.card-title>button{display:flex;align-items:center;gap:3px;margin-left:auto;padding:6px 8px;border:0;border-radius:8px;color:#ef5d75;background:#fff0f0;font-size:8px;cursor:pointer}.card-title>button .material-symbols-outlined{font-size:13px}.settings-card>label{display:grid;gap:6px;margin-top:12px;color:#796765;font-size:9px}.settings-card input{padding:10px;border:1px solid #eaded8;border-radius:9px;outline:0;color:#5d4b4c;background:#fdf9f7;font:10px inherit}.settings-card input:focus{border-color:#ff8998}.save-settings{margin-top:14px;padding:8px 12px;border:0;border-radius:8px;color:#fff;background:#ff6b81;font:700 9px inherit;cursor:pointer}.anniversaries{grid-row:span 2}.anniversary-editor{display:grid;gap:7px}.anniversary-editor>div{display:grid;grid-template-columns:1fr 125px 30px;gap:6px}.anniversary-editor button{display:grid;place-items:center;border:0;border-radius:8px;color:#b99f9d;background:#faf3f0;cursor:pointer}.anniversary-editor .material-symbols-outlined{font-size:15px}.data-actions{display:grid;grid-template-columns:1fr 1fr;gap:8px}.data-actions button,.data-actions label{display:flex;align-items:center;gap:8px;padding:10px;border:1px solid #eee2dc;border-radius:9px;color:#7d6968;background:#fdf9f7;cursor:pointer;text-align:left}.data-actions>label>input{position:absolute;opacity:0;pointer-events:none}.data-actions>.danger{color:#cf5665;border-color:#f3d6d8;background:#fff4f4}.data-actions .material-symbols-outlined{font-size:18px}.data-actions span:last-child{display:grid}.data-actions b{font-size:9px}.data-actions small{margin-top:2px;color:#ad9a97;font-size:7px}.notice{position:fixed;right:28px;bottom:55px;display:flex;align-items:center;gap:6px;padding:9px 12px;border-radius:999px;color:#fff;background:#4e3b3d;box-shadow:0 10px 28px rgba(53,34,36,.2);font-size:9px}.notice .material-symbols-outlined{font-size:15px}.toast-enter-active,.toast-leave-active{transition:.2s}.toast-enter-from,.toast-leave-to{opacity:0;transform:translateY(8px)}
.settings-view>header p{font-size:10px}.card-title p{font-size:10px}.card-title>button{font-size:10px}.settings-card>label{font-size:11px}.settings-card input{font-size:11px}.save-settings{font-size:11px}.data-actions small{font-size:9px}.data-actions b{font-size:11px}.notice{font-size:11px}
</style>
